//loading
export const SET_LOADING = "SET_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";


export const SET_NOTIFY = "SET_NOTIFY";
export const HIDE_NOTIFY = "HIDE_NOTIFY";


export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const LOADING = 'LOADING';

// store
export const FETCH_STORES = 'FETCH_STORES';

// customer
export const OPEN_CUSTOMER_FORM = 'OPEN_CUSTOMER_FORM';
export const CLOSE_CUSTOMER_FORM = 'CLOSE_CUSTOMER_FORM';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const NEW_CUSTOMER = 'NEW_CUSTOMER';
export const NEW_CUSTOMER_CLEAR = 'NEW_CUSTOMER_CLEAR';
export const NEW_CUSTOMER_SAVE = 'NEW_CUSTOMER_SAVE';
export const NEW_CUSTOMER_SAVE_CLOSE = 'NEW_CUSTOMER_SAVE_CLOSE';
export const NEW_CUSTOMER_SAVE_CLEAR = 'NEW_CUSTOMER_SAVE_CLEAR';



// STUDENTS
export const OPEN_STUDENT_FORM = 'OPEN_STUDENT_FORM';
export const CLOSE_STUDENT_FORM = 'CLOSE_STUDENT_FORM';
export const NEW_STUDENT_SAVE = 'NEW_STUDENT_SAVE';
